### ISSUE TITLE
Documentation: https://github.com/azure/azops/wiki/prerequisites 

### ISSUE THREAD

**Issue by zojovano** [Azure/AzOps#420]
**Describe the bug**

$directoryRole = Get-AzureADDirectoryRole -Filter "DisplayName eq 'Directory Readers'" command returns (in Azure Shell):
Get-AzureADDirectoryRole: A parameter cannot be found that matches parameter name 'Filter'. 

**Steps to reproduce**

1. Open Azure Shell
2. Follow steps from https://github.com/azure/azops/wiki/prerequisites#azure-active-directory instructions
3. Execute: $directoryRole = Get-AzureADDirectoryRole -Filter "DisplayName eq 'Directory Readers'"

**Result**

Get-AzureADDirectoryRole: A parameter cannot be found that matches parameter name 'Filter'.

**Comment by daltondhcp** [comment]
Thank you for reporting this @zojovano. 

After investigating, it seems like this issue is related to the custom AzureAD.Standard.Preview module that is running inside of cloud shell. Given that the AzureAD module is on a path towards deprecation, we are looking to update this as per #382.
![image](https://user-images.githubusercontent.com/16622613/132006985-e38567ab-1d5e-43fc-9421-f7559df5c180.png)
![image](https://user-images.githubusercontent.com/16622613/132007012-e5650535-a7de-42e6-b11b-d96487c13117.png)
![image](https://user-images.githubusercontent.com/16622613/132006933-3d22ab86-524e-4098-be2e-83d81521c0f5.png)
https://docs.microsoft.com/en-us/powershell/module/azuread/get-azureaddirectoryrole?view=azureadps-2.0

As a workaround, you can either replace the command in the doc with `$directoryRole = Get-AzureADDirectoryRole | Where-Object {$_.DisplayName -eq "Directory Readers"}` or add the permissions manually via the portal.

**Comment by daltondhcp** [comment]
Will be solved in #382
