### ISSUE TITLE
Role Assignments Ignored

### ISSUE THREAD

**Issue by edm-ms** [Azure/AzOps#431]
The default settings.json has the following defined:

"Core.SkipRole": false

But role assignments are never displayed as .json templates in the repo.

**Comment by daltondhcp** [comment]
We leverage `Get-AzRoleAssignment` to retrieve roleAssignments. `Get-AzRoleAssignment` make calls to the AAD graph to enrich the principalId in a roleAssignment with additional data such objectType and as displayName. 
Since SPNs do not have any AAD permissions by default, it is required to at least grant the AzOps SPN `Directory Reader `permissions in AAD. 
We do call this out in the below doc, but we don't necessarily explain why this is necessary. Will make sure to address in our doc refresh. 
https://github.com/azure/azops/wiki/prerequisites#azure-active-directory

https://github.com/Azure/Enterprise-Scale/blob/aro-const-set-01/docs/EnterpriseScale-Setup-aad-permissions.md

**Comment by edm-ms** [comment]
Yup, I totally missed that. I added the role, re-ran the pull, all role assignments showed up. Thanks.
