### ISSUE TITLE
AzOps - Discovery Performance Issues

### ISSUE THREAD

**Issue by reckitt-maciejglowacki** [Azure/AzOps#438]
AzOps - Pull pipeline of AzOps Accelerator run in Azure DevOps fails to grab information about all of the subscriptions and times out.

SPN has been given privileges over root management group with about 250 subscriptions. The build times out after 4 hours That's what I've set in the pipeline itself. I'm actually not sure if it does anything for that long (or just hangs midway) because log file is too large to browse it effectively.

Here's a screenshot:
<img width="579" alt="2021-10-06_15h40_06" src="https://user-images.githubusercontent.com/92035829/136214915-64a5fb79-326e-41b4-81a6-94ac2e82862e.png">

Has anyone experienced anything like that? Is this tool designed to handle so many subscriptions? Or maybe is it some problem with DevOps pool? Any help will be much appreciated.

**Comment by daltondhcp** [comment]
Understood. Can you try to change back the setting to discover RGs and change the pipeline timeout in ADO to 6 hrs and see if it completes successfully?

**Comment by reckitt-maciejglowacki** [comment]
Hi @daltondhcp Just wanted to check have you managed to look into this issue? Thanks

**Comment by reckitt-maciejglowacki** [comment]
@daltondhcp bump

**Comment by daltondhcp** [comment]
Hey @reckitt-maciejglowacki - we are currently working on this, unfortunately no short term fix. I will make sure to keep the progress updated in this issue.

**Comment by reckitt-maciejglowacki** [comment]
Got it. Thanks for the info.

**Comment by reckitt-maciejglowacki** [comment]
Hi, any update on this?

**Comment by jtracey93** [comment]
Hey @reckitt-maciejglowacki,

Unfortunately we are still investigating this but as a workaround for now you could use Self-hosted agents that have an unlimited run time as per: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#timeouts 

Guidance on creating on self-hosted agents can be found here: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/agents?view=azure-devops&tabs=browser#install

Hope that helps move you forward in the near term 👍

**Comment by reckitt-maciejglowacki** [comment]
Hi. Just wanted to let you know that this update definitely hasn't fixed anything. Quite the opposite.

I'm getting various random errors when trying to execute this in an ADO pipeline. Even when it does run uninterupted (which seems completely random) it times out after an hour.
  
![image](https://user-images.githubusercontent.com/92035829/220321109-97597c08-9058-4502-8a5a-9fe68f6f006b.png)

![image](https://user-images.githubusercontent.com/92035829/220321205-a55f9d76-2464-445b-8944-c2afe479b005.png)

![image](https://user-images.githubusercontent.com/92035829/220321269-03553377-8b40-46de-861b-46ae1b329843.png)

**Comment by Jefajers** [comment]
Hi @reckitt-maciejglowacki, thanks for updating this issue and sharing.

I agree with your experience in regards to a bunch of different errors ultimately causing pipeline executions to fail.

We started seeing this as well once we release 2.0.0 into the wild and determined that majority of the different errors are due to the expanded usage of processing in parallel. When combined with an execution machine containing a "high" throttle limit and "low" amount of cores the errors starts to show a lot.

Our response to this was to implement[ logic in the module  to detect these misalignments](https://github.com/Azure/AzOps/pull/761) and override the throttle limit when detected. In addition to that we created a [wiki for performance considerations](https://github.com/azure/azops/wiki/performance-considerations).

[Since release 2.0.2 improvements are included in AzOps](https://github.com/Azure/AzOps/releases/tag/2.0.2) module intended to resolve the behavior.

Could you confirm if you still have these issues on the latest release? (if yes, then lets re-open the issue).

**Comment by reckitt-maciejglowacki** [comment]
Thank you @Jefajers Latest update does seem to work. I haven't tried it on a resource level yet but it runs well for subscriptions and resource groups.

**Comment by reckitt-maciejglowacki** [comment]
Turns out my enthusiasm was premature..

![image](https://user-images.githubusercontent.com/92035829/234850102-d9976e03-1372-4be5-8899-19515c7b4227.png)

**Comment by daltondhcp** [comment]
Can you share the details of the errors? Same as before or something else?

**Comment by reckitt-maciejglowacki** [comment]
The same I think:

![image](https://user-images.githubusercontent.com/92035829/235122531-3a847153-bda0-41b6-adaa-92d8dfcecd20.png)
![image](https://user-images.githubusercontent.com/92035829/235122544-0939e5bf-2b01-4d85-a16b-ba6dbd088168.png)
![image](https://user-images.githubusercontent.com/92035829/235122554-ca79ed44-d079-4a60-a8d2-4332b8229c1b.png)
![image](https://user-images.githubusercontent.com/92035829/235122561-125f2e84-6fed-41e4-a5f2-36bc820f4a3b.png)

Those seem to appear above certain number of objects but I haven't drilled it down yet.

We're using AZOPS_MODULE_VERSION 2.1.2 and pretty much default settings.json from AzOps-Accelerator project with `"Core.SkipResourceGroup": false`
