### ISSUE TITLE
AzOps not importing RBAC definitions or assigments

### ISSUE THREAD

**Issue by powershellwhizz** [Azure/AzOps#484]
I am very new to DevOps and AzOps in general so apologies if this is dumb or obvious.
When I run the pull action AzOps imports policy defs, assigments, manage groups etc all without issue. Except I cannot find the RBAC json files. I believe they should be in the format of **microsoft.authorization__roleassignments_-5bf6a637.json** as composite ARM templates as per readme file here https://github.com/Azure/AzOps (scroll down to output section).

I do not have a single file like this in my whole repo and I have confirmed in my settings file that my "Core.SkipRole" is set to false.
I even just deployed a new role through AzOps and the push worked; it created the role. However, when the pull followed straight afterwards it did not create the json file in the format above like all other resources that get imported. When I checked the pull acton logs, in the "staus" section the add, commit, merge, push tickboxes are greyed out as if it detected no changes.

**Steps to reproduce**

1. Add any new explicit RBAC role to a management group (though UI or Azops, doesn't matter which)
2. Run the pull action in AzOps
3. Wait for it to finish and notice that no role assigments were synced to the repo and the pull action logs will reflect that no change was detected also.

**Comment by daltondhcp** [comment]
Hey @powershellwhizz,

We leverage Get-AzRoleAssignment to retrieve roleAssignments. Get-AzRoleAssignment make calls to the AAD graph to enrich the principalId in a roleAssignment with additional data such objectType and as displayName.
Since SPNs do not have any AAD permissions by default, it is required to at least grant the AzOps SPN Directory Reader permissions in AAD. Azure/azure-powershell#10039
We do call this out in the below doc, but we don't really explain why this is necessary. We will make sure to address in our doc refresh.
https://github.com/azure/azops/wiki/prerequisites#azure-active-directory

https://github.com/Azure/Enterprise-Scale/blob/aro-const-set-01/docs/EnterpriseScale-Setup-aad-permissions.md

Hope this helps.

/Johan

**Comment by daltondhcp** [comment]
https://github.com/Azure/AzOps/issues/431

**Comment by powershellwhizz** [comment]
Hi Johan,
thanks for the quick response! I was aware what you said might be related but for some reason I can't add the SPN to the Directory readers role. I followed your exact instructions (from your link), when I open the role and then click add, my SPN doesn't show up. This is a brand new empty POC tenant, any idea what would cause that? Anything to do with licensing maybe?
I've also done a google but nothing has come up so far on there being an issue assigning an SPN to this role.

Thanks,

**Comment by daltondhcp** [comment]
Great that it solved the problem! Actually, just tried in my tenant, and I can indeed add SPNs to roles. 
I'll investigate and see what might be causing this.
