### ISSUE TITLE
Validate and Deploy Pipeline fails using latest build

### ISSUE THREAD

**Issue by scotthainesjr** [Azure/AzOps#775]
**Describe the bug**
Anytime I try to push new changes into main, I get this error: 
[Invoke-AzOpsPush] Expecting deploymentList object, it was not found. Error exiting runtime.
**Steps to reproduce**

1. Clone the latest Azure Pipelines code
2. Clone repo after first push, change value of a tag on resource group. (any change or new addition fails)
3. try to merge into main, validation fails

**Screenshots**
![Screenshot 2023-03-14 153537](https://user-images.githubusercontent.com/11492630/225130233-4305d335-9084-4270-8c03-2d4423a59735.png)

**Comment by Jefajers** [comment]
Hi @scotthainesjr thanks for reporting this issue.

I can reproduce, this is a regression issue related to changes in v2.0.0.
We are working on a bugfix to resolve this and ship an updated release.

To resolve your situation right now I would urge you to consider pinning to a AzOps version like 1.9.4 **(then running a pull before any subsequent push)**:

![image](https://user-images.githubusercontent.com/64077181/225183313-e933e1ce-900b-4b77-9c5c-360ca847a006.png)

The nature of the issue affects deployments running v2.0.0 and later when there is “No management group”.

If there is any management group in the discovery the issue does not surface due to different logic used to export the subscription information.
