### ISSUE TITLE
Delete - Invoke-AzOpsPush fails on "-- " in any description field in deleted content

### ISSUE THREAD

**Issue by jsandquist** [Azure/AzOps#787]
**Describe the bug**

This is with AzOps 1.9.4 but the code in question looks the same in current 'main'. See https://github.com/Azure/AzOps/blob/02fc254590b6fce207c4dfafd4c9678a755720cd/src/functions/Invoke-AzOpsPush.ps1#L218

In case an arbitrary/descriptive property happens to contain "-- " this will break some logic in Invoke-AzOps. Typical properties would be DisplayName or Description.

**Steps to reproduce**

1. Create a policy definition via Azure portal
2. Include the text " -- TESTING" in Description or DisplayName
3. Run AzOps Pull to create a Pull Request
4. Validate will hopefully succeed as is normal
5. Delete the policy definition via portal
6. Run AzOps Pull to create a Pull Request
7. Validate will fail on deleted content containing "-- "

The log output is not very clear - but thankfully the source code is available here :-)

**Screenshots**

![image](https://user-images.githubusercontent.com/1163202/232765057-6f7c8abd-d105-4de2-a8d9-45fe676f9723.png)

**Comment by daltondhcp** [comment]
Thank you for reporting, I am able to reproduce the issue when trying to delete a resource with '--' in the displayName/description.

As a side note, if I may ask, is there a particular reason why you are running validate after pull? Since it is coming from the platform, there shouldn't be a need to do any validation? We changed the default behavior of this in https://github.com/Azure/AzOps-Accelerator/pull/132, so might be worth taking a look at as well.

**Comment by jsandquist** [comment]
Thanks @daltondhcp - I had completely missed that change so thanks for sharing. We do use a similar condition for push already!
