### ISSUE TITLE
Guidance on integrating AzOps with policyDefinitions and policyAssignments from the Azure/Enterprise-Scale repository

### ISSUE THREAD

**Issue by Xitric** [Azure/AzOps#808]
First of all, thank you for a great tool!

**Context**

We are looking into adopting AzOps for managing our Azure tenant management groups and associated policies using AzOps, but we are also interested in relying on the efforts of upstream repositories such as [Azure/Enteprise-Scale](https://github.com/Azure/Enterprise-Scale) and [Azure/ALZ-Bicep](https://github.com/Azure/ALZ-Bicep), specifically when it comes to modules (BRM/CRML) and `policyDefinitions`/`policyAssignments`.

In terms of using Bicep modules from the enterprise scale reference implementations, the process seems quite straightforward:

1. Have custom pipelines release the modules to our private container registry for Bicep modules.
    1. Optionally: Rely on a public container registry in the future (unlikely for us, but still a possibility)
1. Write deployment templates in AzOps for deploying a specific version of each module to our Azure tenant.

However, when it comes to the modules for `policyDefinitions` and `policyAssignments`, the process becomes a bit hazy, since AzOps has first-party support for clearly representing `policyDefinitions` and `policyAssignments` in the git repository. What we _could_ do is:

1. Have a custom pipeline for releasing the `policyDefinitions` module from Azure/ALZ-Bicep to our private container registry.
1. Reference the new `policyDefinitions` module in a deployment template in our AzOps git repository.
1. Wait for the module to be deployed by the push pipeline.
1. Execute the pull pipeline to create first-party `policyDefinitions` and `policyAssignments` templates in the AzOps repository (in addition to the upstream module).

However, we like to avoid using the module for policy definitions and assignments for a few reasons:

1. We like the visibility that AzOps grants in terms of what policies are deployed and assigned at which scopes - the module does not provide this as clearly.
1. We like the ability to review new policies via pull requests before merging and eventually pushing them - using the module we would need a separate process outside of AzOps for estimating the impact of deploying a new module version.
1. We require the ability to apply new policies as audit only, since deploying new enforced policies could have adverse effects on our production environments.

**Describe the solution you'd like**

We can see that the projects [Azure/Enteprise-Scale](https://github.com/Azure/Enterprise-Scale) and [Azure/ALZ-Bicep](https://github.com/Azure/ALZ-Bicep) try to maintain a single source of truth in terms of `policyDefinitions` by making use of (frankly) ad-hoc scripting to convert `policyDefinitions` from Azure/Enterprise-Scale (https://github.com/Azure/Enterprise-Scale/tree/main/src/resources/Microsoft.Authorization/policyDefinitions) into a Bicep module in Azure/ALZ-Bicep (https://github.com/Azure/ALZ-Bicep/blob/main/.github/scripts/Invoke-LibraryUpdate.ps1 and https://github.com/Azure/ALZ-Bicep/blob/main/.github/scripts/Invoke-PolicyToBicep.ps1).

What we could do ourselves is to make similar scripting for converting the same upstream `policyDefinitions` into a format fit for AzOps. However, we fear that this is a flaky approach since Azure/Enterprise-Scale could make changes to how they represent `policyDefinitions` any time, breaking our integrations.

Thus, just like the project Azure/ALZ-Bicep maintains scripting to stay up to date, we thought it would be fitting for the AzOps repository to maintain such scripting as well. The goal would be to provide a first-party set of always-up-to-date policy definitions from Azure/Enterprise-Scale ready to be used together with AzOps. We hope that a solution would make it easy to perform a PR-based workflow allowing:

1. Upstream changes to be reviewed before merging
1. Changes to `enforcementMode` of new and modified `policyAssignments` to be changed to avoid impacting running systems

This could be part of the accelerator even to make it easier for enterprises to adopt Azure/Enteprise-Scale without having to rely on either portal flows or the imperative pipelines from Azure/ALZ-Bicep. But any solution really would be interesting to us!

We look forward to hearing your thoughts on this!

**Comment by Jefajers** [comment]
Hi @Xitric, bare with us and I will get back to you on this during next week:steam_locomotive:.

**Comment by Jefajers** [comment]
Thanks for staying with us @Xitric.

Let’s see if I have understood the scenario correctly.

Your intent is to combine the ALZ-Bicep module together with AzOps as you described to achieve orchestration of deployments with AzOps as the deployment vehicle for the ALZ-Bicep module.

In addition to this you would prefer to use AzOps to fully manage policy’s natively with the AzOps PowerShell module. Due to this you envision a need to stay up-to-date with the up-stream policy changes. You correctly point out this is something already performed in the ALZ-Bicep and Azure landing zones Terraform module repositories.

We have looked at the possibility of subscribing to the upstream policy’s as you suggest and concluded for now that this is not in line with the project goals of AzOps module as a deployment vehicle.

With that said you could of course add this yourself to your desired environments like the references you point out. As a side note you could consider, using ALZ-Bicep to perform the policy updates from up-stream and then let AzOps pull them back for continued management.

**Comment by daltondhcp** [comment]
Closing this question issue, please continue conversation if further questions arise.

**Comment by Xitric** [comment]
Hello @Jefajers and thanks for the reply - I just returned from holiday, which is why am am responding this late.

> As a side note you could consider, using ALZ-Bicep to perform the policy updates from up-stream and then let AzOps pull them back for continued management.

If I understand you correctly, is the consensus in the long term that AzOps should not be used as the initial deployment vehicle for Azure landing zones? Rather, should customers deploy their landing zones initially via Portal experiences or the Bicep/Terraform projects, and only later manage changes to the environment via AzOps?

Then we are back at solving the issue of staying up to date with changes in the upstream accelerator repositories, unless we accept a mixture of declarative deployments via AzOps and imperative deployments via the Bicep and Terraform accelerator pipelines.

> We have looked at the possibility of subscribing to the upstream policy’s as you suggest and concluded for now that this is not in line with the project goals of AzOps module as a deployment vehicle.

I am wondering then, if it is in line with the AzOps accelerator project to subscribe to the upstream policies. We were hoping that AzOps was considered a viable project by Azure for managing the entire life cycle of a landing zone (including initial deployment and _all_ updates). In this case, it would make sense to work on an accelerator project to provide a similar deployment experience to that in [Azure/Enteprise-Scale](https://github.com/Azure/Enterprise-Scale) and [Azure/ALZ-Bicep](https://github.com/Azure/ALZ-Bicep), rather than relying on deployments out of band via other tools.

In the meantime, we will work on a custom solution for subscribing to changes in policies in the upstream [Azure/Enteprise-Scale](https://github.com/Azure/Enterprise-Scale) project, and we hope that some day this can be considered in scope of AzOps or a corresponding accelerator repository for Azure Landing Zones _via AzOps_.

**Comment by daltondhcp** [comment]
To provide further clarity, AzOps can indeed be used for the initial deployment of Azure Landing Zones. 
However, Jesper's point was that AzOps is designed as a versatile and flexible deployment pipeline/vehicle for any Azure template or scope, and we currently intend to maintain it that way. We aim to avoid additional complexity by not implementing tighter integrations at this stage.

Nevertheless, due to the nature of AzOps, you have the freedom to customize the pipelines to suit your specific requirements. For example, you can synchronize policies from the upstream repository or apply any other type of customization. Many customers have already taken advantage of this capability by utilizing code snippets from the Bicep/Terraform repositories.

Furthermore, if you create a customized solution, we would be delighted to publish it as a sample in the accelerator repository. This way, it can serve as a valuable resource for others looking to leverage AzOps for their specific use cases.
